name: Generated App Tests
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ 14.x, 16.x ]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
            */*/node_modules
          key: PUSH-${{ runner.os }}-${{matrix.node-version}}-${{ hashFiles(./packages/amplication-data-service-generator/**/package-lock.json)}}
          restore-keys: |
            GA-E2E-${{ runner.os }}-${{matrix.node-version}}
            GA-E2E-${{ runner.os }}-

      - name: Update npm
        run: npm i -g npm@8.1.2

      - run: npm ci

      - name: Install packages' dependencies
        run: lerna bootstrap --scope @amplication/data-service-generator --include-dependencies

      - name: Generate test data service
        run: npm run generate-test-data-service

      - name: Build Data Service Generator
        run: lerna run prisma:generate --scope @amplication/data-service-generator --include-dependencies

      - name: Build Data Service Generator
        run: lerna run build --scope @amplication/data-service-generator --include-dependencies

      - name: Run test data service's tests
        run: lerna run test --scope=@amplication/data-service-generator

      - name: Run Data Service Generator E2E test
        run: lerna run test:e2e --scope=@amplication/data-service-generator
